<a href="https://colab.research.google.com/github/pacomm5/PLANTILLAS2/blob/main/datasets/Part%201%20-%20Artificial%20Neural%20Networks%20(ANN)/ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clonamos el repositorio para obtener los dataSet

In [ ]:
#!git clone https://github.com/joanby/deeplearning-az.git

Cloning into 'deeplearning-az'...
remote: Enumerating objects: 71, done.
remote: Counting objects: 100% (71/71), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 10167 (delta 35), reused 44 (delta 20), pack-reused 10096
Receiving objects: 100% (10167/10167), 236.96 MiB | 24.11 MiB/s, done.
Resolving deltas: 100% (60/60), done.
Checking out files: 100% (10110/10110), done.


In [1]:
!git clone https://github.com/pacomm5/deeplearning-az
# esto nos abrirá provisionalmente una carpeta con todos los datos en temporal de google colab, en este caso la carpeta deeplearning-az

Cloning into 'deeplearning-az'...
remote: Enumerating objects: 10196, done.
remote: Counting objects: 100% (100/100), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 10196 (delta 52), reused 78 (delta 40), pack-reused 10096
Receiving objects: 100% (10196/10196), 281.16 MiB | 40.18 MiB/s, done.
Resolving deltas: 100% (77/77), done.
Checking out files: 100% (10119/10119), done.


# Damos acceso a nuestro Drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Test it

In [ ]:
!ls '/content/drive/My Drive' 

'2019_097 Audi Service News - Campaña Modelo de predicción de abandono.msg'
'31 de agosto.xlsx'
'Acuerdos_Preformance meeting_Junio17- Jarmauto_v1.pdf'
 C3942BF2-8A67-4F4F-B37D-7656F1E356DD.doc
'Chalet Loranca.doc'
 characters-simpsons.csv
'Colab Notebooks'
'Copia de Clasificacion-1.ipynb'
'Copia de Clasificación-2.ipynb'
'Copia de Clustering.ipynb'
'Copia de EDA-Feature_Selection.ipynb'
'Copia de Feature_Engineering.ipynb'
'Copia de Regression.ipynb'
'Copia de requirements.txt'
'Copy of 1. Les verbes en -ER-Rosa (1).pdf'
'Copy of 1. Les verbes en -ER-Rosa.pdf'
 curriculum.doc
 curriculum.doc.gdoc
'Escaneado 21 ago 2016 3.21.pdf'
 HS3ABA.ZIP
 HS4EF4.ZIP
'HS4EF4.ZIP (Unzipped Files)'
 HS6.ZIP
 HS7859.ZIP
'HS7859.ZIP (Unzipped Files)'
 HSA151.ZIP
 HSA9B3.ZIP
 HSD86A.ZIP
'HSD86A.ZIP (Unzipped Files)'
 Inversión.gsheet
 jarmauto
 JARMAUTO2
 Justificante.pdf
 kaggle
 libros
'parque jarmauto (1).docx.gdoc'
'parque jarmauto.docx'
'parque jarmauto.docx.gdoc'
'Performance meeting17_Comun_v8

# Google colab tools

In [3]:
from google.colab import files # Para manejar los archivos y, por ejemplo, exportar a su navegador
import glob # Para manejar los archivos y, por ejemplo, exportar a su navegador
from google.colab import drive # Montar tu Google drive

# Instalar dependendias

In [4]:
!pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1310 sha256=1a38e225ed75d4dae0687f57527f26e871b25d46bc27f5c723136d93d06c9ec7
  Stored in directory: /root/.cache/pip/wheels/46/ef/c3/157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built sklearn


# Instalar Theano

In [5]:
!pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning git://github.com/Theano/Theano.git to /tmp/pip-req-build-cctpydfn
  Running command git clone -q git://github.com/Theano/Theano.git /tmp/pip-req-build-cctpydfn
  fatal: unable to connect to github.com:
  github.com[0: 140.82.112.4]: errno=Connection timed out

ERROR: Command errored out with exit status 128: git clone -q git://github.com/Theano/Theano.git /tmp/pip-req-build-cctpydfn Check the logs for full command output.


# Instalar Tensorflow y Keras


In [6]:
!pip install keras
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# Redes Neuronales Artificales

# Cómo importar las librerías


In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importar el data set


In [8]:
dataset = pd.read_csv('/content/deeplearning-az/datasets/Part 1 - Artificial Neural Networks (ANN)/Churn_Modelling.csv')


In [9]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [11]:
X = dataset.iloc[:, 3:13].values # incluye desde la tercera a la 13, no inclusive. esta es la matriz de características. 
y = dataset.iloc[:, 13].values # aqui solo la variable dependiente. 

In [12]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [13]:
y

array([1, 0, 1, ..., 1, 1, 0])

# Parte 1 - Pre procesado de datos

# Codificar datos categóricos

tenemos dos variables categoricas

In [14]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

labelencoder_X_1 = LabelEncoder() # la primera variable categorica le llamamos X_1
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1]) # cogemos la columna 1 y hacemos un fittrasnform


In [15]:
X # aqui ya vemos que no aparece la columna pais, sino que la ha codificado con 0 y 1, y 2

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [16]:
labelencoder_X_2 = LabelEncoder() # aqui lo mismo con la otra. 
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])


In [17]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [18]:
# ahora lo que nos toca es separar los 0 1 2 y lo que sea. 
onehotencoder = ColumnTransformer( # 
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [1])],   
    remainder='passthrough'                        
)
X = onehotencoder.fit_transform(X)
X = X[:, 1:] # con esto evitamos el problema de la multicolinealidad, es decir si tenemos tres paises, no ponemos tres columnas sino dos. 
# en el genero igual, si tenemos dos quitamos una y nos quedamos con una. 

In [29]:
X

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

# Dividir el data set en conjunto de entrenamiento y conjunto de testing

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Escalado de variables

In [21]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [22]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [23]:
X_test

array([[ 1.75486502, -0.57369368, -0.55204276, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [-0.5698444 , -0.57369368, -1.31490297, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-0.5698444 ,  1.74309049,  0.57162971, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-0.5698444 ,  1.74309049, -0.74791227, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [ 1.75486502, -0.57369368, -0.00566991, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [ 1.75486502, -0.57369368, -0.79945688, ...,  0.64259497,
        -1.03227043,  1.61255917]])

# Parte 2 - Construir la RNA

# Importar Keras y librerías adicionales


In [26]:

import keras
from keras.models import Sequential # esta es para inicializar 
from keras.layers import Dense # esta es para crear las capas intermedias. 

# Inicializar la RNA

In [27]:
classifier = Sequential() # creamos el modelo, lo inicicializamos. 

# Añadir las capas de entrada y primera capa oculta


In [30]:
X.shape

(10000, 11)

In [31]:
# empezamos a meter capas, la de entrada y la capa oculta. 
classifier.add(Dense(units = 6, kernel_initializer = "uniform",  
                     activation = "relu", input_dim = 11))
# imput dim son las variables que tenemos. Utilizamos relu (rectificador) para activar 
# en la capa de salida utilizaremos la sigmoide. esta en los apuntes anteriores lo que es cada una. 
# unit es el número de nodos de la capa oculta. una regla  o consejo es fijar la media entre los nodos de entrada y salida. como tenemos 11 de entrada y 1 de salida la media ponemos 6
# kernel_initializer es como iniciamos esos pesos, uniform serán pequeños y cercanos a 0.

# Añadir la segunda capa oculta

In [32]:
classifier.add(Dense(units = 6, kernel_initializer = "uniform",  activation = "relu"))
# no hace falta meter el input dim, porque ya lo conoce la anterior que son 6 nodos. 

# Añadir la capa de salida

In [33]:
classifier.add(Dense(units = 1, kernel_initializer = "uniform",  activation = "sigmoid"))
# como dijimos arriba para la de salida utilizamos la función de activación sigmoid. 
# units 1, ya que es la de salida. Ya que solo queremos clasificar solo en dos categorías.

# Compilar la RNA

In [34]:
classifier.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])
# Vamos a compilar. optimizer adam (buscar el conjunto optimo de pesos y hemos elegido adam)
# loss la función de perdidas es la que minimiza el error. binary_crossentropy 
# metric  son las matericas que queremos que utilice para mejorar en entrenamiento

# Ajustamos la RNA al Conjunto de Entrenamiento. ME QUEDO AQUI

In [ ]:
classifier.fit(X_train, y_train,  batch_size = 10, epochs = 100)
# lote de 10 en 10 y epoch numeros de veces que queramos que haga. pasa 100 veces por la red neuronal. 

Epoch 1/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4829 - accuracy: 0.7960
Epoch 2/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4262 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4210 - accuracy: 0.8039
Epoch 4/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4173 - accuracy: 0.8249
Epoch 5/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4160 - accuracy: 0.8278
Epoch 6/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4140 - accuracy: 0.8313
Epoch 7/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4128 - accuracy: 0.8316
Epoch 8/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4114 - accuracy: 0.8320
Epoch 9/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4100 - accuracy: 0.8326
Epoch 10/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4090 - accura

# Parte 3 - Evaluar el modelo y calcular predicciones finales

# Predicción de los resultados con el Conjunto de Testing

In [ ]:
y_pred  = classifier.predict(X_test)
y_pred = (y_pred>0.5)

# Elaborar una matriz de confusión

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

## Parte 4 - Evaluar, mejorar y Ajustar la RNA


### Evaluar la **RNA**


In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [ ]:
def build_classifier():
  classifier = Sequential()
  classifier.add(Dense(units = 6, kernel_initializer = "uniform", activation = "relu", input_dim = 11))
  classifier.add(Dense(units = 6, kernel_initializer = "uniform", activation = "relu"))
  classifier.add(Dense(units = 1, kernel_initializer = "uniform", activation = "sigmoid"))
  classifier.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])
  return classifier

In [ ]:
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, nb_epoch = 100)
accuracies = cross_val_score(estimator=classifier, X = X_train, y = y_train, cv = 10, n_jobs=-1, verbose = 1)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  10 out of  10 | elapsed:   18.9s finished


In [ ]:
mean = accuracies.mean()
variance = accuracies.std()

### Mejorar la RNA

#### Regularización de Dropout para evitar el *overfitting*


### Ajustar la *RNA*


In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
def build_classifier(optimizer):
  classifier = Sequential()
  classifier.add(Dense(units = 6, kernel_initializer = "uniform",  activation = "relu", input_dim = 11))
  classifier.add(Dense(units = 6, kernel_initializer = "uniform",  activation = "relu"))
  classifier.add(Dense(units = 1, kernel_initializer = "uniform",  activation = "sigmoid"))
  classifier.compile(optimizer = optimizer, loss = "binary_crossentropy", metrics = ["accuracy"])
  return classifier


In [ ]:
classifier = KerasClassifier(build_fn = build_classifier)

In [ ]:
parameters = {
    'batch_size' : [25,32],
    'nb_epoch' : [100, 500], 
    'optimizer' : ['adam', 'rmsprop']
}

In [ ]:
grid_search = GridSearchCV(estimator = classifier, 
                           param_grid = parameters, 
                           scoring = 'accuracy', 
                           cv = 10)
grid_search = grid_search.fit(X_train, y_train)

best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

288/288 [==============================] - 0s 2ms/step - loss: 0.5595 - accuracy: 0.7960
Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
 25/288 [=>............................] - ETA: 0s - loss: 0.6893 - accuracy: 0.7776

KeyboardInterrupt: ignored